{% set name = "rq_geo_toolkit" %}
{% set version = "2025.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rq_geo_toolkit-{{ version }}.tar.gz
  sha256: d18a2d37d3204cbf16562270614dbcdf1e3c13547ed30a3c73b0205053f9975e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=1.0
    - shapely >=2.0.6
    - pyarrow >=16.0.0
    - rich >=12.0.0
    - geopy >=2.0.0
    - python-duckdb >=1.1.2
    - psutil >=5.6.2
    - packaging >=17.0

test:
  imports:
    - rq_geo_toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kraina-ai/rq_geo_toolkit
  summary: Collection of geo related functions for reuse in other geospatial libraries
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RaczeQ
